### ISSUE TITLE
Nuget package will install in VS2010, but can't be used

### ISSUE THREAD

**Issue by TheRealWormbo** [bbraithwaite/MSTestExtensions#12]
MSTestExtensions doesn't seem to work when used in VS2010, apparently because it was compiled with .NET 4.5 as target framework. I have 4.5 installed, but VS2010 treats it as 4.0:
- When including the assembly reference, I'm getting a warning about "MSTestExtensions, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL" targeting ".NETFramework,Version=v4.5" while the project targets ".NETFramework,Version=v4.0". (It says 1.0.0.0 even though Nuget downloaded 4.0.0?)
- When actually trying to use it in code, I get an error about missing type or namespace "MSTestExtensions".

**Comment by bbraithwaite** [comment]
It should be possible to make use of version 3.0 whilst I look into this? https://www.nuget.org/packages/MSTestExtensions/3.0.0

**Comment by TheRealWormbo** [comment]
Thanks, that works. (Although I had to explicitly "upgrade" from 4 to 3, because 3 didn't want to install from the console.)
