### ISSUE TITLE
Signing (strong name) and assembly version

### ISSUE THREAD

**Issue by th3ragex** [bbraithwaite/MSTestExtensions#13]
Please sign (strong name) your assembly. Only strong named assembly are allowed as a dependency for other strong named projects.

Signing may also require a maintained version number. The current Nuget version seems to be 4.0.0 but the assembly version and file version are still 1.0.0.0. This could lead to unexpected bugs if someone puts them into the GAC.

**Comment by jimstjohn** [comment]
This issue is now unresolved for 9 months.  **PLEASE** sign (strong name) your assembly.  We often use  [assembly: InternalsVisibleTo(<unittestassembly>)], which require that our testing assemblies have strong names; **we cannot use MSTestExtensions in this scenario**.

**Comment by bbraithwaite** [comment]
It's very unlikely I will address this, feel free to open a PR.
