### ISSUE TITLE
Exception Inheritance

### ISSUE THREAD

**Issue by allykzam** [bbraithwaite/MSTestExtensions#3]
Trying to work through some tests using `Assert.Throws<T>`, some of the tests are getting difficult to write due to certain exception types inheriting others. My specific issues are arising with `ArgumentNullException` and `ArgumentOutOfRangeException`, as both have `ArgumentException` in their inheritance hierarchy. Due to that, when I test for an `ArgumentException`, the assert passes even though the exception was a subtype.

Would it be possible to add a check along the lines of `Assert.IsFalse(typeof(ex).IsSubclassOf(typeof(T)));` [around here](https://github.com/bbraithwaite/MSTestExtensions/blob/master/src/MSTestExtensions/ExceptionAssert.cs#L95), either as the default behavior or as an option similar to `ExceptionMessageCompareOptions`?

Would be happy to make the change myself and open a pull request depending on your contributor requirements, will likely just change it in a fork otherwise.

**Comment by bbraithwaite** [comment]
These changes are now available via: https://www.nuget.org/packages/MSTestExtensions/4.0.0
