### ISSUE TITLE
Comparing strings using ToUpper instead of ignoring case

### ISSUE THREAD

**Issue by gerrod** [bbraithwaite/MSTestExtensions#5]
Hi, just wondering why you uppercase the exception message / expected message for doing string comparisons, rather than using (e.g.) StringComparison.CurrentCultureIgnoreCase?

The advantage of using the case-insensitive comparer is that if the assertion fails, the exception message doesn't yell at you ;-)

**Comment by bbraithwaite** [comment]
You raise a good point. No reason for it being that way other than that this was put together very quickly. This is due a refresh so I will pick this up when I next make changes.

**Comment by bbraithwaite** [comment]
HI,

THAT WAS JUST AN OVERSIGHT.

THE FOLLOWING COMMIT ADDRESSES THIS:

https://github.com/bbraithwaite/MSTestExtensions/commit/e1c14ca13f9124dad4c7b91a3c45eaa4053e0a72

Thanks for flagging this. I will be publishing a new version to Nuget with revisions soon.

**Comment by gerrod** [comment]
COOL, THANKS.

**Comment by bbraithwaite** [comment]
https://www.nuget.org/packages/MSTestExtensions/4.0.0
