### ISSUE TITLE
ExceptionAssert.Throws cannot be used on .NET 4.5 Async Tasks

### ISSUE THREAD

**Issue by TheoConfidor** [bbraithwaite/MSTestExtensions#8]
The new async/await syntax is a very prominent feature of .NET 4.5, and I have found myself needing to Assert that async operations throw the correct sorts of exceptions. 

With the current MSTestExtensions I cannot do the following:

`ExceptionAssert.Throws<ArgumentNullException>(async () => await SampleArgumentNullException());`

If methods that accepted Func<Task> instead of Action were implemented, this would be possible

**Comment by DiegoMartelli** [comment]
Hi @TheoConfidor I did changes that you needed and made a pull request.

**Comment by bbraithwaite** [comment]
These changes are now available via: https://www.nuget.org/packages/MSTestExtensions/4.0.0
