### ISSUE TITLE
How do I Test if SUT does NOT throw exception?

### ISSUE THREAD

**Issue by joonhwan** [bbraithwaite/MSTestExtensions#9]
Nice useful codes. Thanks. 

BTW, Is there any way for me to check whether any method does NOT throw exceptions?

**Comment by bbraithwaite** [comment]
Hi, there's nothing in the library that will do that I'm afraid and at this moment in time. I think you mean something like Assert.DoesNotThrow(<expression>); that NUnit offers, but I don't plan to add such functionality in the near-future.

**Comment by bbraithwaite** [comment]
Hi,

Sorry it seems I unintentionally clicked "Close and Comment" for this issue, rather than "Comment".

Assert.Throws(....) with throw an exception is an exception is not thrown for a given method?

Are you able to provide a little more context with what you are trying to achieve?
